# Numpy

–ú–∞—Ç–µ—Ä–∏–∞–ª—ã:
* –ú–∞–∫—Ä—É—à–∏–Ω –°.–í. "–õ–µ–∫—Ü–∏—è 1: –ë–∏–±–ª–∏–æ—Ç–µ–∫–∞ Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## –ó–∞–¥–∞—á–∏ –¥–ª—è —Å–æ–≤–º–µ—Å—Ç–Ω–æ–≥–æ —Ä–∞–∑–±–æ—Ä–∞

1. –°–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞—Ç—å –¥–≤—É—Ö–º–µ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤ `arr` —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ (4, 7), —Å–æ—Å—Ç–æ—è—â–∏–π –∏–∑ —Å–ª—É—á–∞–π–Ω—ã—Ö –¥–µ–π—Å—Ç–≤–∏—Ç–µ–ª—å–Ω—ã—Ö —á–∏—Å–µ–ª, —Ä–∞–≤–Ω–æ–º–µ—Ä–Ω–æ —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω—ã—Ö –≤ –¥–∏–∞–ø–∞–∑–æ–Ω–µ –æ—Ç 0 –¥–æ 20. –ù–æ—Ä–º–∞–ª–∏–∑–æ–≤–∞—Ç—å –∑–Ω–∞—á–µ–Ω–∏—è –º–∞—Å—Å–∏–≤–∞ —Å –ø–æ–º–æ—â—å—é –ø—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏—è –≤–∏–¥–∞  $ùëéùë•+ùëè$  —Ç–∞–∫, —á—Ç–æ –ø–æ—Å–ª–µ –Ω–æ—Ä–º–∞–ª–∏–∑–∞—Ü–∏–∏ –º–∞–∫—Å–∏–º–∞–ª—å–Ω—ã–π —ç–ª–µ–º–µ–Ω—Ç –º–∞—Åc–∏–≤–∞ –±—É–¥–µ—Ç —Ä–∞–≤–µ–Ω 1.0, –º–∏–Ω–∏–º–∞–ª—å–Ω—ã–π 0.0

In [2]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. –°–æ–∑–¥–∞—Ç—å –º–∞—Ç—Ä–∏—Ü—É 8 –Ω–∞ 10 –∏–∑ —Å–ª—É—á–∞–π–Ω—ã—Ö —Ü–µ–ª—ã—Ö (–∏—Å–ø–æ–ª—å–∑—É—è –º–æ–¥—É–ª—å `numpy.random`) —á–∏—Å–µ–ª –∏–∑ –¥–∏–∞–ø–æ–∑–æ–Ω–∞ –æ—Ç 0 –¥–æ 10 –∏ –Ω–∞–π—Ç–∏ –≤ –Ω–µ–π —Å—Ç—Ä–æ–∫—É (–µ–µ –∏–Ω–¥–µ–∫—Å –∏ –≤—ã–≤–µ—Å—Ç–∏ —Å–∞–º—É —Å—Ç—Ä–æ–∫—É), –≤ –∫–æ—Ç–æ—Ä–æ–π —Å—É–º–º–∞ –∑–Ω–∞—á–µ–Ω–∏–π –º–∏–Ω–∏–º–∞–ª—å–Ω–∞.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. –ù–∞–π—Ç–∏ –µ–≤–∫–ª–∏–¥–æ–≤–æ —Ä–∞—Å—Å—Ç–æ—è–Ω–∏–µ –º–µ–∂–¥—É –¥–≤—É–º—è –æ–¥–Ω–æ–º–µ—Ä–Ω—ã–º–∏ –≤–µ–∫—Ç–æ—Ä–∞–º–∏ –æ–¥–∏–Ω–∞–∫–æ–≤–æ–π —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. –†–µ—à–∏—Ç—å –º–∞—Ç—Ä–∏—á–Ω–æ–µ —É—Ä–∞–≤–Ω–µ–Ω–∏–µ `A*X*B=-C` - –Ω–∞–π—Ç–∏ –º–∞—Ç—Ä–∏—Ü—É `X`. –ì–¥–µ `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## –õ–∞–±–æ—Ä–∞—Ç–æ—Ä–Ω–∞—è —Ä–∞–±–æ—Ç–∞ ‚Ññ1

–ó–∞–º–µ—á–∞–Ω–∏–µ: –ø—Ä–∏ —Ä–µ—à–µ–Ω–∏–∏ –¥–∞–Ω–Ω—ã—Ö –∑–∞–¥–∞—á –Ω–µ –ø–æ–¥—Ä–∞–∑—É–º–µ–≤–∞–µ—Ç—Å—è –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è —Ü–∏–∫–ª–æ–≤ –∏–ª–∏ –≥–µ–Ω–µ—Ä–∞—Ç–æ—Ä–æ–≤ Python, –µ—Å–ª–∏ –≤ –∑–∞–¥–∞–Ω–∏–∏ –Ω–µ —Å–∫–∞–∑–∞–Ω–æ –æ–±—Ä–∞—Ç–Ω–æ–≥–æ. –†–µ—à–µ–Ω–∏–µ –¥–æ–ª–∂–Ω–æ –æ–ø–∏—Ä–∞—Ç—å—Å—è –Ω–∞ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª–∞ –±–∏–±–ª–∏–æ—Ç–µ–∫–∏ `numpy`.

1. –§–∞–π–ª `minutes_n_ingredients.csv` —Å–æ–¥–µ—Ä–∂–∏—Ç –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ–± –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–µ —Ä–µ—Ü–µ–ø—Ç–∞, –≤—Ä–µ–º–µ–Ω–∏ –µ–≥–æ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –≤ –º–∏–Ω—É—Ç–∞—Ö –∏ –∫–æ–ª–∏—á–µ—Å—Ç–≤–µ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤. –°—á–∏—Ç–∞–π—Ç–µ –¥–∞–Ω–Ω—ã–µ –∏–∑ —ç—Ç–æ–≥–æ —Ñ–∞–π–ª–∞ –≤ –≤–∏–¥–µ –º–∞—Å—Å–∏–≤–∞ `numpy` —Ç–∏–ø–∞ `int32`, –∏—Å–ø–æ–ª—å–∑—É—è `np.loadtxt`. –í—ã–≤–µ–¥–∏—Ç–µ –Ω–∞ —ç–∫—Ä–∞–Ω –ø–µ—Ä–≤—ã–µ 5 —Å—Ç—Ä–æ–∫ –º–∞—Å—Å–∏–≤–∞.

In [75]:
minutes_n_ingredients = np.loadtxt('./minutes_n_ingredients.csv', dtype='int32', skiprows=1, delimiter=',')
minutes_n_ingredients[0:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. –í—ã—á–∏—Å–ª–∏—Ç–µ —Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ, –º–∏–Ω–∏–º—É–º, –º–∞–∫—Å–∏–º—É–º –∏ –º–µ–¥–∏–∞–Ω—É –ø–æ –∫–∞–∂–¥–æ–º—É –∏–∑ —Å—Ç–æ–ª–±—Ü–æ–≤, –∫—Ä–æ–º–µ –ø–µ—Ä–≤–æ–≥–æ.

In [76]:
id = minutes_n_ingredients[:, 0]
time = minutes_n_ingredients[:, 1]
amount = minutes_n_ingredients[:, 2]

In [45]:
print('—Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –ø–æ —Å—Ç–æ–ª–±—Ü—É "–≤—Ä–µ–º—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è": ' + str(time.mean()))
print('–º–∏–Ω–∏–º—É–º –ø–æ —Å—Ç–æ–ª–±—Ü—É "–≤—Ä–µ–º—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è": ' + str(time.min()))
print('–º–∞–∫—Å–∏–º—É–º –ø–æ —Å—Ç–æ–ª–±—Ü—É "–≤—Ä–µ–º—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è": ' + str(time.max()))
print('–º–µ–¥–∏–∞–Ω–∞ –ø–æ —Å—Ç–æ–ª–±—Ü—É "–≤—Ä–µ–º—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è": ' + str(np.median(time)))
print('—Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –ø–æ —Å—Ç–æ–ª–±—Ü—É "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": ' + str(amount.mean()))
print('–º–∏–Ω–∏–º—É–º –ø–æ —Å—Ç–æ–ª–±—Ü—É "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": ' + str(amount.min()))
print('–º–∞–∫—Å–∏–º—É–º –ø–æ —Å—Ç–æ–ª–±—Ü—É "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": ' + str(amount.max()))
print('–º–µ–¥–∏–∞–Ω–∞ –ø–æ —Å—Ç–æ–ª–±—Ü—É "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": ' + str(np.median(amount)))

—Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –ø–æ —Å—Ç–æ–ª–±—Ü—É "–≤—Ä–µ–º—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è": 21601.00169
–º–∏–Ω–∏–º—É–º –ø–æ —Å—Ç–æ–ª–±—Ü—É "–≤—Ä–µ–º—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è": 0
–º–∞–∫—Å–∏–º—É–º –ø–æ —Å—Ç–æ–ª–±—Ü—É "–≤—Ä–µ–º—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è": 2147483647
–º–µ–¥–∏–∞–Ω–∞ –ø–æ —Å—Ç–æ–ª–±—Ü—É "–≤—Ä–µ–º—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è": 40.0
—Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –ø–æ —Å—Ç–æ–ª–±—Ü—É "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": 9.05528
–º–∏–Ω–∏–º—É–º –ø–æ —Å—Ç–æ–ª–±—Ü—É "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": 1
–º–∞–∫—Å–∏–º—É–º –ø–æ —Å—Ç–æ–ª–±—Ü—É "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": 39
–º–µ–¥–∏–∞–Ω–∞ –ø–æ —Å—Ç–æ–ª–±—Ü—É "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": 9.0


3. –û–≥—Ä–∞–Ω–∏—á—å—Ç–µ —Å–≤–µ—Ä—Ö—É –∑–Ω–∞—á–µ–Ω–∏—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è —Ä–µ—Ü–µ–ø—Ç–∞ –∑–Ω–∞—á–µ–Ω–∏–µ–º –∫–≤–∞–Ω—Ç–∏–ª—è $q_{0.75}$. 

In [46]:
limiter = np.quantile(minutes_n_ingredients, 0.75)
np.clip(time, 0, limiter)

array([[ 60.],
       [ 25.],
       [ 10.],
       ...,
       [ 65.],
       [  5.],
       [140.]])

4. –ü–æ—Å—á–∏—Ç–∞–π—Ç–µ, –¥–ª—è —Å–∫–æ–ª—å–∫–∏—Ö —Ä–µ—Ü–µ–ø—Ç–æ–≤ —É–∫–∞–∑–∞–Ω–∞ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å, —Ä–∞–≤–Ω–∞—è –Ω—É–ª—é. –ó–∞–º–µ–Ω–∏—Ç–µ –¥–ª—è —Ç–∞–∫–∏—Ö —Å—Ç—Ä–æ–∫ –∑–Ω–∞—á–µ–Ω–∏–µ –≤ –¥–∞–Ω–Ω–æ–º —Å—Ç–æ–ª–±—Ü–µ –Ω–∞ 1.

In [77]:
print('–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ä–µ—Ü–µ–ø—Ç–æ–≤, –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∫–æ—Ç–æ—Ä—ã—Ö —Ä–∞–≤–Ω–∞ –Ω—É–ª—é: '+str(np.sum(time==0)))
minutes_n_ingredients[time==0] = 1

–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ä–µ—Ü–µ–ø—Ç–æ–≤, –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∫–æ—Ç–æ—Ä—ã—Ö —Ä–∞–≤–Ω–∞ –Ω—É–ª—é: 479


5. –ü–æ—Å—á–∏—Ç–∞–π—Ç–µ, —Å–∫–æ–ª—å–∫–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö —Ä–µ—Ü–µ–ø—Ç–æ–≤ –Ω–∞—Ö–æ–¥–∏—Ç—Å—è –≤ –¥–∞—Ç–∞—Å–µ—Ç–µ.

In [53]:
len(np.unique(id))

100000

6. –°–∫–æ–ª—å–∫–æ –∏ –∫–∞–∫–∏—Ö —Ä–∞–∑–ª–∏—á–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π –∫–æ–ª-–≤–∞ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –ø—Ä–∏—Å—É—Ç–≤—É–µ—Ç –≤ —Ä–µ—Ü–µ–ø—Ç–∞—Ö –∏–∑ –¥–∞—Ç–∞—Å–µ—Ç–∞?

In [74]:
print('–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π —Å—Ç–æ–ª–±—Ü–∞ "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": '+str(len(np.unique(amount))))
print('—É–Ω–∏–∫–∞–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è: '+str(np.unique(amount)))

–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π —Å—Ç–æ–ª–±—Ü–∞ "–∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤": 37
—É–Ω–∏–∫–∞–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. –°–æ–∑–¥–∞–π—Ç–µ –≤–µ—Ä—Å–∏—é –º–∞—Å—Å–∏–≤–∞, —Å–æ–¥–µ—Ä–∂–∞—â—É—é –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é —Ç–æ–ª—å–∫–æ –æ —Ä–µ—Ü–µ–ø—Ç–∞—Ö, —Å–æ—Å—Ç–æ—è—â–∏—Ö –Ω–µ –±–æ–ª–µ–µ —á–µ–º –∏–∑ 5 –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤.

In [73]:
new_minutes_n_ingredients = minutes_n_ingredients[amount < 6]
print(new_minutes_n_ingredients)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. –î–ª—è –∫–∞–∂–¥–æ–≥–æ —Ä–µ—Ü–µ–ø—Ç–∞ –ø–æ—Å—á–∏—Ç–∞–π—Ç–µ, —Å–∫–æ–ª—å–∫–æ –≤ —Å—Ä–µ–¥–Ω–µ–º –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –ø—Ä–∏—Ö–æ–¥–∏—Ç—Å—è –Ω–∞ –æ–¥–Ω—É –º–∏–Ω—É—Ç—É —Ä–µ—Ü–µ–ø—Ç–∞. –ù–∞–π–¥–∏—Ç–µ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ —ç—Ç–æ–π –≤–µ–ª–∏—á–∏–Ω—ã –¥–ª—è –≤—Å–µ–≥–æ –¥–∞—Ç–∞—Å–µ—Ç–∞

In [56]:
np.max(amount/time)

24.0

9. –í—ã—á–∏—Å–ª–∏—Ç–µ —Å—Ä–µ–¥–Ω–µ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –¥–ª—è —Ç–æ–ø-100 —Ä–µ—Ü–µ–ø—Ç–æ–≤ —Å –Ω–∞–∏–±–æ–ª—å—à–µ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å—é

In [58]:
top_100_average = minutes_n_ingredients[minutes_n_ingredients[:, 1].argsort()[::-1]][0:100, 2:].mean()
print(top_100_average)

6.61


10. –í—ã–±–µ—Ä–∏—Ç–µ —Å–ª—É—á–∞–π–Ω—ã–º –æ–±—Ä–∞–∑–æ–º –∏ –≤—ã–≤–µ–¥–∏—Ç–µ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ 10 —Ä–∞–∑–ª–∏—á–Ω—ã—Ö —Ä–µ—Ü–µ–ø—Ç–∞—Ö

11. –í—ã–≤–µ–¥–∏—Ç–µ –ø—Ä–æ—Ü–µ–Ω—Ç —Ä–µ—Ü–µ–ø—Ç–æ–≤, –∫–æ–ª-–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –≤ –∫–æ—Ç–æ—Ä—ã—Ö –º–µ–Ω—å—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ.

In [61]:
len(amount[amount < amount.mean()])/len(amount)

0.58802

12. –ù–∞–∑–æ–≤–µ–º "–ø—Ä–æ—Å—Ç—ã–º" —Ç–∞–∫–æ–π —Ä–µ—Ü–µ–ø—Ç, –¥–ª–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –∫–æ—Ç–æ—Ä–æ–≥–æ –Ω–µ –±–æ–ª—å—à–µ 20 –º–∏–Ω—É—Ç –∏ –∫–æ–ª-–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –≤ –∫–æ—Ç–æ—Ä–æ–º –Ω–µ –±–æ–ª—å—à–µ 5. –°–æ–∑–¥–∞–π—Ç–µ –≤–µ—Ä—Å–∏—é –¥–∞—Ç–∞—Å–µ—Ç–∞ —Å –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–º —Å—Ç–æ–ª–±—Ü–æ–º, –∑–Ω–∞—á–µ–Ω–∏—è–º–∏ –∫–æ—Ç–æ—Ä–æ–≥–æ —è–≤–ª—è—é—Ç—Å—è 1, –µ—Å–ª–∏ —Ä–µ—Ü–µ–ø—Ç –ø—Ä–æ—Å—Ç–æ–π, –∏ 0 –≤ –ø—Ä–æ—Ç–∏–≤–Ω–æ–º —Å–ª—É—á–∞–µ.

In [115]:
is_recipe_easy = np.concatenate((minutes_n_ingredients, np.zeros((len(minutes_n_ingredients), 1), dtype='int32')), 1)
is_recipe_easy[:, 3][(is_recipe_easy[:, 1] < 21) & (is_recipe_easy[:, 2] < 6)] = 1
print(is_recipe_easy)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. –í—ã–≤–µ–¥–∏—Ç–µ –ø—Ä–æ—Ü–µ–Ω—Ç "–ø—Ä–æ—Å—Ç—ã—Ö" —Ä–µ—Ü–µ–ø—Ç–æ–≤ –≤ –¥–∞—Ç–∞—Å–µ—Ç–µ

In [118]:
np.sum(is_recipe_easy[:, 3] == 1)/np.sum(is_recipe_easy[:, 3] == 0)

0.11040785280433503

14. –†–∞–∑–¥–µ–ª–∏–º —Ä–µ—Ü–µ–ø—Ç—ã –Ω–∞ –≥—Ä—É–ø–ø—ã –ø–æ —Å–ª–µ–¥—É—é—â–µ–º—É –ø—Ä–∞–≤–∏–ª—É. –ù–∞–∑–æ–≤–µ–º —Ä–µ—Ü–µ–ø—Ç—ã –∫–æ—Ä–æ—Ç–∫–∏–º–∏, –µ—Å–ª–∏ –∏—Ö –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –º–µ–Ω–µ–µ 10 –º–∏–Ω—É—Ç; —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—ã–º–∏, –µ—Å–ª–∏ –∏—Ö –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –±–æ–ª–µ–µ 10, –Ω–æ –º–µ–Ω–µ–µ 20 –º–∏–Ω—É—Ç; –∏ –¥–ª–∏–Ω–Ω—ã–º–∏, –µ—Å–ª–∏ –∏—Ö –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –Ω–µ –º–µ–Ω–µ–µ 20 –º–∏–Ω—É—Ç. –°–æ–∑–¥–∞–π—Ç–µ —Ç—Ä–µ—Ö–º–µ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤, –≥–¥–µ –Ω—É–ª–µ–≤–∞—è –æ—Å—å –æ—Ç–≤–µ—á–∞–µ—Ç –∑–∞ –Ω–æ–º–µ—Ä –≥—Ä—É–ø–ø—ã (–∫–æ—Ä–æ—Ç–∫–∏–π, —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—ã–π –∏–ª–∏ –¥–ª–∏–Ω–Ω—ã–π —Ä–µ—Ü–µ–ø—Ç), –ø–µ—Ä–≤–∞—è –æ—Å—å - –∑–∞ —Å–∞–º —Ä–µ—Ü–µ–ø—Ç –∏ –≤—Ç–æ—Ä–∞—è –æ—Å—å - –∑–∞ —Ö–∞—Ä–∞–∫—Ç–µ—Ä–∏—Å—Ç–∏–∫–∏ —Ä–µ—Ü–µ–ø—Ç–∞. –í—ã–±–µ—Ä–∏—Ç–µ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ä–µ—Ü–µ–ø—Ç–æ–≤ –∏–∑ –∫–∞–∂–¥–æ–π –≥—Ä—É–ø–ø—ã —Ç–∞–∫–∏–º –æ–±—Ä–∞–∑–æ–º, —á—Ç–æ–±—ã –±—ã–ª–æ –≤–æ–∑–º–æ–∂–Ω–æ —Å—Ñ–æ—Ä–º–∏—Ä–æ–≤–∞—Ç—å —Ç—Ä–µ—Ö–º–µ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤. –í—ã–≤–µ–¥–∏—Ç–µ —Ñ–æ—Ä–º—É –ø–æ–ª—É—á–µ–Ω–Ω–æ–≥–æ –º–∞—Å—Å–∏–≤–∞.

In [135]:
groups = np.array([1, 2, 3, 4, 5, 6, 7, 8])
groups.reshape(2,2,2)

groups = [
    [[1, 2], [4, 7]],
    [3, 4],
    [5, 6]
]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])